---
docstring: |
  This example workflow file shows how to invoke commands and worklets, the structure intentionally
  mimics that of GitHUB actions, however, the keys you see here are all there is. This is it, end
  of story.

  Running commands, as you can see below, then running commands, looks just like running commands
  on in a GitHUB Workflow, just add the 'run' key with a multi-line string

  Running worklets, is similar to that of a GitHUB action, where you define the action/worklet
  via 'uses' key, and provides arguments to the action/worklet via the 'with' key

steps:
- name: Run commands via cijoe.run()
  run: |
    cat /proc/cpuinfo
    hostname

- name: Invoke the test_runner worklet
  uses: run_tests
  with:
    args: "--pyargs joe.core.selftest"

- name: Invoke the report generator worklet
  uses: report
