---
default_language_version:
  python: python3

repos:
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.1
  hooks:
  - id: yamlfmt
    name: YAML-format
    args:
    - '--mapping=2'
    - '--sequence=2'
    - '--offset=0'
    - '--width=120'
    - '--preserve-quotes'
    types: [file]
    files: \.(yaml|yml)$

- repo: https://github.com/psf/black
  rev: '22.3.0'
  hooks:
  - id: black
    name: Python-format-black
- repo: https://github.com/pycqa/isort
  rev: '5.10.1'
  hooks:
  - id: isort
    name: Python-format-isort
    args:
    - '--profile=black'
    - '--line-length=88'
- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    name: Python-lint-flake8
    args:
    - '--extend-ignore=E203,E501' # ignore "whitespace before ':'"; ignore line length
    exclude: (ctypes_mapping\/api\.py)$

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: shellcheck
    name: Shell-lint
