---
# Declare the transport for command-execution, currently local and ssh are implemented, should be a
# breeze to add mosh as a transport as well.
#transport:
#  ssh:  # The SSH options are passed verbatim to paramiko; see https://www.paramiko.org/
#    hostname: test_target
#    port: 22
#    username: root
